name: Java CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: maven:3.9.9-eclipse-temurin-21
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build with Maven
        run: mvn clean test package
      
      - name: Upload JAR artifacts
        uses: actions/upload-artifact@v4
        with:
          name: application-jar
          path: ./target/*.jar